name: Trigger Netlify Build
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy to Netlify"
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install  # Adjust based on your package manager

      - name: Build project
        run: npm run build  # Ensure this matches your build script

      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.MY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.MY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: dist/final-project/browser  # Update based on actual build output
